# site settings
title: Pavan Kulkarni
subtitle: The Life and Musings
email: pavankcsc@gmail.com
description: Should be Interesting to know more about this great man
baseurl: "/pavankulkarni" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Pavan Kulkarni
street_address: 
city: Bangalore
state: Karnataka,
country: India
phone: <i> Available on Request </i>

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9

# social settings
500px_url:
facebook_url: https://www.facebook.com/ashish.rao.m
github_url: https://github.com/ashishrao7
gitlab_url: https://gitlab.com/rao_art
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/ashish-rao-mangalore-4a888a26/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/MangaloreAshish

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-gist
  
